{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# AI-Driven Emergency Care Coordination (Simplified)\n",
    "\n",
    "**Simplified notebook maintaining core medical logic while reducing complexity**\n",
    "\n",
    "- Advice-only system for ED coordination workflows\n",
    "- Protected: ESC 0/1h troponin logic, phase2_bundle interface, event logging\n",
    "- Simplified: Configuration, UI code, error handling, unnecessary abstractions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === CORE CONFIG (Protected Interface) ===\n",
    "import os\n",
    "from pathlib import Path\n",
    "from typing import Dict, Any\n",
    "\n",
    "# Simple config - removed over-engineered freezing mechanism\n",
    "CONFIG = {\n",
    "    \"RUN_UI\": True,\n",
    "    \"RUN_PIPELINE\": True,\n",
    "    \"DATA_ROOT\": \"/kaggle/working\",\n",
    "    \"EVENT_LOG_PATH\": \"/kaggle/working/event_log.jsonl\",\n",
    "    \"MODEL_BUNDLE_PATH\": \"/kaggle/working/ed_phase2_model_thr_patched(1).joblib\",\n",
    "    \"EQUIPMENT_STATUS_PATH\": \"/kaggle/working/equipment_status.csv\",\n",
    "}\n",
    "\n",
    "# Create directories\n",
    "for path_key in [\"DATA_ROOT\", \"EVENT_LOG_PATH\", \"EQUIPMENT_STATUS_PATH\"]:\n",
    "    path = Path(CONFIG[path_key])\n",
    "    path.parent.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "print(\"CONFIG initialized ->\", CONFIG[\"EVENT_LOG_PATH\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === EVENT LOGGING (Protected Interface) ===\n",
    "import json\n",
    "from datetime import datetime, timezone\n",
    "\n",
    "def _append_event(ev: dict):\n",
    "    \"\"\"Protected interface - maintain exact signature and semantics\"\"\"\n",
    "    ev = {\"ts\": datetime.utcnow().isoformat() + \"Z\", **(ev or {})}\n",
    "    with open(CONFIG[\"EVENT_LOG_PATH\"], \"a\", encoding=\"utf-8\") as f:\n",
    "        f.write(json.dumps(ev, ensure_ascii=False) + \"\\n\")\n",
    "\n",
    "print(\"Event logging ready\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === MEDICAL CALCULATOR UTILITIES (Simplified) ===\n",
    "from typing import Optional, List, Union\n",
    "\n",
    "def safe_float(value, default=None):\n",
    "    \"\"\"Simple float conversion\"\"\"\n",
    "    if value is None:\n",
    "        return default\n",
    "    try:\n",
    "        return float(str(value).replace(\",\", \".\"))\n",
    "    except (ValueError, TypeError):\n",
    "        return default\n",
    "\n",
    "def safe_int(value, default=None):\n",
    "    \"\"\"Simple int conversion\"\"\"\n",
    "    if value is None:\n",
    "        return default\n",
    "    try:\n",
    "        return int(float(str(value).replace(\",\", \".\")))\n",
    "    except (ValueError, TypeError):\n",
    "        return default\n",
    "\n",
    "def safe_bool(value):\n",
    "    \"\"\"Simple bool conversion\"\"\"\n",
    "    if isinstance(value, bool):\n",
    "        return value\n",
    "    s = str(value).strip().lower()\n",
    "    return s in {\"1\", \"true\", \"yes\", \"y\", \"ja\", \"on\"}\n",
    "\n",
    "print(\"Utility functions ready\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === CORE MEDICAL CALCULATORS (Simplified) ===\n",
    "\n",
    "def calc_qsofa(vitals: dict) -> dict:\n",
    "    \"\"\"Quick SOFA score\"\"\"\n",
    "    rr = safe_float(vitals.get(\"rr\") or vitals.get(\"resp_rate\"))\n",
    "    sbp = safe_float(vitals.get(\"sbp\") or vitals.get(\"systolic\"))\n",
    "    gcs = safe_float(vitals.get(\"gcs\"))\n",
    "    avpu = str(vitals.get(\"avpu\", \"\")).upper()[:1]\n",
    "    \n",
    "    altered = (gcs is not None and gcs < 15) or avpu in {\"V\", \"P\", \"U\"}\n",
    "    \n",
    "    score = 0\n",
    "    if rr is not None and rr >= 22: score += 1\n",
    "    if sbp is not None and sbp <= 100: score += 1\n",
    "    if altered: score += 1\n",
    "    \n",
    "    return {\"name\": \"qSOFA\", \"score\": score}\n",
    "\n",
    "def calc_heart(data: dict) -> dict:\n",
    "    \"\"\"HEART score for chest pain\"\"\"\n",
    "    age = safe_int(data.get(\"age\"))\n",
    "    hist = safe_int(data.get(\"heart_history\"), 0)\n",
    "    ecg = safe_int(data.get(\"heart_ecg\"), 0)\n",
    "    risk = safe_int(data.get(\"heart_risk\"), 0)\n",
    "    \n",
    "    # Age scoring\n",
    "    age_score = 0\n",
    "    if age is not None:\n",
    "        if age >= 65: age_score = 2\n",
    "        elif age >= 45: age_score = 1\n",
    "    \n",
    "    # Troponin scoring (simplified)\n",
    "    trop = safe_float(data.get(\"troponin\"))\n",
    "    uln = safe_float(data.get(\"troponin_uln\"))\n",
    "    trop_score = 0\n",
    "    if trop is not None and uln:\n",
    "        ratio = trop / uln\n",
    "        if ratio > 3: trop_score = 2\n",
    "        elif ratio > 1: trop_score = 1\n",
    "    \n",
    "    total = hist + ecg + age_score + risk + trop_score\n",
    "    return {\"name\": \"HEART\", \"score\": int(total)}\n",
    "\n",
    "def calc_wells_pe(data: dict) -> dict:\n",
    "    \"\"\"Wells score for PE\"\"\"\n",
    "    score = 0.0\n",
    "    \n",
    "    if safe_bool(data.get(\"dvt_signs\")): score += 3.0\n",
    "    if safe_bool(data.get(\"pe_most_likely\")): score += 3.0\n",
    "    \n",
    "    hr = safe_float(data.get(\"hr\") or data.get(\"pulse\"))\n",
    "    if hr and hr > 100: score += 1.5\n",
    "    \n",
    "    if safe_bool(data.get(\"immobilized\")) or safe_bool(data.get(\"recent_surgery_4w\")): score += 1.5\n",
    "    if safe_bool(data.get(\"prev_vte\")): score += 1.5\n",
    "    if safe_bool(data.get(\"hemoptysis\")): score += 1.0\n",
    "    if safe_bool(data.get(\"cancer_active\")): score += 1.0\n",
    "    \n",
    "    tier = \"likely\" if score > 4 else \"unlikely\"\n",
    "    return {\"name\": \"WELLS_PE\", \"score\": score, \"tier2\": tier}\n",
    "\n",
    "print(\"Core medical calculators ready\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === TROPONIN DELTA ASSESSMENT (Protected Logic) ===\n",
    "from datetime import datetime\n",
    "\n",
    "def assess_troponin_delta(series):\n",
    "    \"\"\"Protected interface - ESC 0/1h for Roche hs-cTnT (exact 60-min pairing)\"\"\"\n",
    "    if not series:\n",
    "        return {\"available\": False}\n",
    "    \n",
    "    # Normalize to ng/L and sort by time\n",
    "    ser = []\n",
    "    for ts, v, u in series:\n",
    "        if v is None:\n",
    "            continue\n",
    "        try:\n",
    "            v = float(v)\n",
    "            if isinstance(u, str) and (\"µg/l\" in u.lower() or \"ug/l\" in u.lower()):\n",
    "                v *= 1000.0\n",
    "        except (ValueError, TypeError):\n",
    "            continue\n",
    "        ser.append((ts, v))\n",
    "    \n",
    "    ser = sorted(ser, key=lambda x: (x[0] or datetime.min))\n",
    "    \n",
    "    if len(ser) < 2:\n",
    "        return {\n",
    "            \"available\": True, \"prev\": ser[-1][1] if ser else None, \"curr\": ser[-1][1] if ser else None,\n",
    "            \"delta_abs\": 0.0, \"delta_pct\": None, \"flag\": False,\n",
    "            \"dt_min\": None, \"rule01h\": None, \"reason\": \"needs_serial\"\n",
    "        }\n",
    "    \n",
    "    # Latest sample as t1; search exact 60-min predecessor\n",
    "    t1_ts, t1 = ser[-1]\n",
    "    pair = None\n",
    "    \n",
    "    for j in range(len(ser) - 2, -1, -1):\n",
    "        t0_ts, t0 = ser[j]\n",
    "        if t0_ts is None or t1_ts is None:\n",
    "            continue\n",
    "        dt_min = round((t1_ts - t0_ts).total_seconds() / 60)\n",
    "        if dt_min == 60:\n",
    "            pair = (t0_ts, t0, dt_min)\n",
    "            break\n",
    "    \n",
    "    if pair:\n",
    "        _, t0, dt = pair\n",
    "        dv = t1 - t0\n",
    "        dp = (abs(dv) / t0 * 100.0) if t0 else None\n",
    "        \n",
    "        # ESC 0/1h thresholds (Roche hs-cTnT)\n",
    "        if (t0 >= 52.0) or (dv >= 5.0):\n",
    "            label = \"rule_in\"\n",
    "        elif (t0 < 12.0) and (dv < 3.0):\n",
    "            label = \"rule_out\"\n",
    "        else:\n",
    "            label = \"observe\"\n",
    "        \n",
    "        return {\n",
    "            \"available\": True, \"prev\": t0, \"curr\": t1,\n",
    "            \"delta_abs\": dv, \"delta_pct\": dp, \"flag\": (label == \"rule_in\"),\n",
    "            \"dt_min\": dt, \"rule01h\": label, \"reason\": \"ok\"\n",
    "        }\n",
    "    \n",
    "    # No exact 60-min pair\n",
    "    t0_ts, t0 = ser[-2]\n",
    "    dv = t1 - t0\n",
    "    dp = (abs(dv) / t0 * 100.0) if t0 else None\n",
    "    gap = round((t1_ts - (t0_ts or t1_ts)).total_seconds() / 60) if t0_ts and t1_ts else None\n",
    "    \n",
    "    return {\n",
    "        \"available\": True, \"prev\": t0, \"curr\": t1,\n",
    "        \"delta_abs\": dv, \"delta_pct\": dp, \"flag\": False,\n",
    "        \"dt_min\": gap, \"rule01h\": None, \"reason\": \"no_01h_pair\"\n",
    "    }\n",
    "\n",
    "print(\"Troponin delta assessment ready (ESC 0/1h protected)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === PHASE2 BUNDLE (Protected Interface) ===\n",
    "\n",
    "def phase2_bundle(vitals: dict, labs: dict, context: dict = None) -> dict:\n",
    "    \"\"\"Protected interface - maintain exact return structure\"\"\"\n",
    "    context = context or {}\n",
    "    \n",
    "    # Calculate scores\n",
    "    qsofa = calc_qsofa(vitals)\n",
    "    heart = calc_heart({**vitals, **labs})\n",
    "    wells_pe = calc_wells_pe({**vitals, **labs, **context})\n",
    "    \n",
    "    # D-dimer assessment (simplified)\n",
    "    d_val = safe_float(labs.get(\"d_dimer\"))\n",
    "    age = safe_int(vitals.get(\"age\") or context.get(\"age\"))\n",
    "    pregnant = safe_bool(context.get(\"pregnant\"))\n",
    "    \n",
    "    d_assess = {\"available\": False}\n",
    "    if d_val:\n",
    "        thr = 500.0\n",
    "        if age and age > 50 and not pregnant:\n",
    "            thr = float(age) * 10.0\n",
    "        d_assess = {\n",
    "            \"available\": True,\n",
    "            \"value_ug_per_l\": d_val,\n",
    "            \"thr_ug_per_l\": thr,\n",
    "            \"ok_below_thr\": d_val < thr\n",
    "        }\n",
    "    \n",
    "    # Troponin series assessment (protected logic)\n",
    "    series = []\n",
    "    for item in labs.get(\"troponin_series\", []):\n",
    "        if isinstance(item, dict):\n",
    "            ts = None\n",
    "            if item.get(\"time\"):\n",
    "                try:\n",
    "                    ts = datetime.fromisoformat(str(item[\"time\"]).replace(\"Z\", \"\"))\n",
    "                except ValueError:\n",
    "                    ts = None\n",
    "            series.append((ts, item.get(\"value\"), item.get(\"unit\", \"ng/L\")))\n",
    "    \n",
    "    t_assess = assess_troponin_delta(series) if len(series) >= 2 else {\"available\": False}\n",
    "    \n",
    "    # Build one-liners\n",
    "    ones = []\n",
    "    ones.append(f\"qSOFA={qsofa['score']}  HEART={heart['score']}  Wells-PE={wells_pe['score']:.1f}\")\n",
    "    \n",
    "    if d_assess.get(\"available\"):\n",
    "        ones.append(\n",
    "            f\"D-dimer {int(d_assess['value_ug_per_l'])} vs thr {int(d_assess['thr_ug_per_l'])} μg/L → \"\n",
    "            f\"{'OK' if d_assess['ok_below_thr'] else 'High'}\"\n",
    "        )\n",
    "    \n",
    "    # hs-cTnT 0/1h one-liner (protected format)\n",
    "    if t_assess.get(\"available\"):\n",
    "        r = t_assess.get(\"rule01h\")\n",
    "        if r is None:\n",
    "            dt = t_assess.get(\"dt_min\")\n",
    "            ones.append(\n",
    "                \"hs-cTnT 0/1h: OBSERVE — \" +\n",
    "                (\"needs serial\" if dt is None else f\"no 60-min pair (latest gap={int(dt)} min)\")\n",
    "            )\n",
    "        else:\n",
    "            lbl = r.replace(\"_\", \"-\").upper()\n",
    "            ones.append(\n",
    "                f\"hs-cTnT 0/1h: {lbl} (t0={t_assess['prev']:.0f}, t1={t_assess['curr']:.0f}, \"\n",
    "                f\"Δ={t_assess['delta_abs']:.0f} ng/L; 60 min)\"\n",
    "            )\n",
    "    \n",
    "    # Protected return structure\n",
    "    return {\n",
    "        \"one_liners\": ones,\n",
    "        \"scores\": {\n",
    "            \"qsofa\": qsofa[\"score\"],\n",
    "            \"heart\": heart[\"score\"],\n",
    "            \"wells_pe\": wells_pe[\"score\"]\n",
    "        },\n",
    "        \"labs\": {\n",
    "            \"d_dimer\": d_assess.get(\"value_ug_per_l\"),\n",
    "            \"d_dimer_thr\": d_assess.get(\"thr_ug_per_l\"),\n",
    "            \"trop_prev\": t_assess.get(\"prev\"),\n",
    "            \"trop_curr\": t_assess.get(\"curr\"),\n",
    "            \"trop_delta\": t_assess.get(\"delta_abs\"),\n",
    "            \"trop_delta_pct\": t_assess.get(\"delta_pct\"),\n",
    "            \"trop_flag\": t_assess.get(\"flag\"),\n",
    "            \"trop_rule01h\": t_assess.get(\"rule01h\"),\n",
    "            \"trop_dt_min\": t_assess.get(\"dt_min\")\n",
    "        },\n",
    "        \"signals\": {\n",
    "            \"acs_rulein\": (t_assess.get(\"rule01h\") == \"rule_in\"),\n",
    "            \"acs_ruleout\": (t_assess.get(\"rule01h\") == \"rule_out\")\n",
    "        }\n",
    "    }\n",
    "\n",
    "print(\"Phase2 bundle ready (protected interface)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === HL7 PARSER (Protected Interface) ===\n",
    "import re\n",
    "from datetime import datetime\n",
    "\n",
    "def parse_hl7_labs(txt: str) -> dict:\n",
    "    \"\"\"Protected interface - parse Trop/D-dimer/INR/Bili/Albumin from HL7 OBX\"\"\"\n",
    "    trops, dd, others = [], [], {\"bilirubin\": None, \"inr\": None, \"albumin\": None}\n",
    "    \n",
    "    for ln in re.split(r'[\\r\\n]+', (txt or \"\").strip()):\n",
    "        if not ln.startswith(\"OBX|\"):\n",
    "            continue\n",
    "        \n",
    "        parts = ln.split(\"|\")\n",
    "        if len(parts) < 7:\n",
    "            continue\n",
    "        \n",
    "        obx3, obx5, obx6 = parts[3], parts[5], parts[6]\n",
    "        obx14 = parts[14] if len(parts) > 14 else None\n",
    "        \n",
    "        # Parse timestamp\n",
    "        ts = None\n",
    "        if obx14:\n",
    "            m = re.search(r'(\\d{8})(\\d{6})?', obx14)\n",
    "            if m:\n",
    "                try:\n",
    "                    ts = datetime.strptime(m.group(1) + (m.group(2) or \"000000\"), \"%Y%m%d%H%M%S\")\n",
    "                except ValueError:\n",
    "                    pass\n",
    "        \n",
    "        # Parse value\n",
    "        try:\n",
    "            v = float(str(obx5).replace(\",\", \".\"))\n",
    "        except (ValueError, TypeError):\n",
    "            mm = re.search(r'[-+]?\\d*\\.?\\d+', str(obx5))\n",
    "            v = float(mm.group(0)) if mm else None\n",
    "        \n",
    "        if v is None:\n",
    "            continue\n",
    "        \n",
    "        u = obx6 or \"\"\n",
    "        name = (obx3 or ln).upper()\n",
    "        \n",
    "        # Categorize by name\n",
    "        if \"TROP\" in name:\n",
    "            trops.append((ts, v, u or \"ng/L\"))\n",
    "        elif any(k in name for k in [\"D-DIMER\", \"DDIMER\", \"D DIMER\"]):\n",
    "            dd.append((ts, v, u or \"μg/L FEU\"))\n",
    "        elif \"BILIRUBIN\" in name or \"BILI\" in name:\n",
    "            if others[\"bilirubin\"] is None:\n",
    "                others[\"bilirubin\"] = v / 17.1 if u.lower() in {\"umol/l\", \"µmol/l\"} else v\n",
    "        elif \"INR\" in name and others[\"inr\"] is None:\n",
    "            others[\"inr\"] = v\n",
    "        elif \"ALBUMIN\" in name and others[\"albumin\"] is None:\n",
    "            others[\"albumin\"] = v / 10.0 if u.lower() in {\"g/l\", \"g l\", \"gl\"} else v\n",
    "    \n",
    "    return {\"troponin\": trops, \"d_dimer\": dd, \"others\": others}\n",
    "\n",
    "print(\"HL7 parser ready (protected interface)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === SIMPLIFIED UI (Streamlined ipywidgets) ===\n",
    "if CONFIG.get(\"RUN_UI\"):\n",
    "    try:\n",
    "        import ipywidgets as widgets\n",
    "        from IPython.display import display\n",
    "        import json\n",
    "        \n",
    "        # Input widgets\n",
    "        vitals_input = widgets.Textarea(\n",
    "            value='{\"rr\":24,\"sbp\":95,\"gcs\":14,\"hr\":120,\"temp\":38.6,\"avpu\":\"V\",\"age\":68,\"sao2\":97}',\n",
    "            description='Vitals JSON',\n",
    "            layout=widgets.Layout(width='100%', height='80px')\n",
    "        )\n",
    "        \n",
    "        labs_input = widgets.Textarea(\n",
    "            value='{\"d_dimer\":780,\"troponin_series\":[{\"time\":\"2025-08-20T05:00:00Z\",\"value\":18},{\"time\":\"2025-08-20T09:00:00Z\",\"value\":78}]}',\n",
    "            description='Labs JSON',\n",
    "            layout=widgets.Layout(width='100%', height='80px')\n",
    "        )\n",
    "        \n",
    "        context_input = widgets.Textarea(\n",
    "            value='{\"pregnant\":false,\"pe_most_likely\":true,\"dvt_signs\":false}',\n",
    "            description='Context JSON',\n",
    "            layout=widgets.Layout(width='100%', height='60px')\n",
    "        )\n",
    "        \n",
    "        hl7_input = widgets.Textarea(\n",
    "            value='OBX|1|NM|TROPONIN T||78|ng/L|||H||F|||20250820090000\\nOBX|2|NM|D-DIMER||780|ug/L|||H||F|||20250820090000',\n",
    "            description='HL7 Paste',\n",
    "            layout=widgets.Layout(width='100%', height='80px')\n",
    "        )\n",
    "        \n",
    "        # Buttons\n",
    "        apply_hl7_btn = widgets.Button(description=\"Apply HL7 → Labs\", button_style='info')\n",
    "        compute_btn = widgets.Button(description=\"Compute + Log\", button_style='primary')\n",
    "        output_area = widgets.Output()\n",
    "        \n",
    "        def apply_hl7(b):\n",
    "            with output_area:\n",
    "                output_area.clear_output()\n",
    "                try:\n",
    "                    labs = json.loads(labs_input.value or \"{}\")\n",
    "                    parsed = parse_hl7_labs(hl7_input.value)\n",
    "                    \n",
    "                    # Merge parsed data\n",
    "                    for k, v in parsed[\"others\"].items():\n",
    "                        if v is not None:\n",
    "                            labs[k] = v\n",
    "                    \n",
    "                    # Add troponin series\n",
    "                    if parsed[\"troponin\"]:\n",
    "                        series = []\n",
    "                        for t, v, u in parsed[\"troponin\"]:\n",
    "                            series.append({\n",
    "                                \"time\": t.isoformat() + \"Z\" if t else None,\n",
    "                                \"value\": v,\n",
    "                                \"unit\": u\n",
    "                            })\n",
    "                        labs[\"troponin_series\"] = series\n",
    "                    \n",
    "                    # Add D-dimer\n",
    "                    if parsed[\"d_dimer\"] and \"d_dimer\" not in labs:\n",
    "                        _, v, u = sorted(parsed[\"d_dimer\"], key=lambda x: x[0] or datetime.min)[-1]\n",
    "                        labs[\"d_dimer\"] = v\n",
    "                    \n",
    "                    labs_input.value = json.dumps(labs, ensure_ascii=False)\n",
    "                    print(\"HL7 data merged successfully\")\n",
    "                except Exception as e:\n",
    "                    print(f\"Error parsing HL7: {e}\")\n",
    "        \n",
    "        def compute(b):\n",
    "            with output_area:\n",
    "                output_area.clear_output()\n",
    "                try:\n",
    "                    vitals = json.loads(vitals_input.value or \"{}\")\n",
    "                    labs = json.loads(labs_input.value or \"{}\")\n",
    "                    context = json.loads(context_input.value or \"{}\")\n",
    "                    \n",
    "                    bundle = phase2_bundle(vitals, labs, context)\n",
    "                    _append_event({\"type\": \"phase2_bundle\", \"bundle\": bundle})\n",
    "                    \n",
    "                    print(\"=== RESULTS ===\")\n",
    "                    for line in bundle[\"one_liners\"]:\n",
    "                        print(line)\n",
    "                    \n",
    "                    print(f\"\\n=== SIGNALS ===\")\n",
    "                    signals = bundle[\"signals\"]\n",
    "                    if signals[\"acs_rulein\"]:\n",
    "                        print(\"⚠️  ACS RULE-IN: Page cardiology (advice-only), prep cath-lab checklist\")\n",
    "                    elif signals[\"acs_ruleout\"]:\n",
    "                        print(\"✅ ACS RULE-OUT: De-prioritize ACS pathway, continue non-ACS evaluation\")\n",
    "                    else:\n",
    "                        print(\"📊 Continue observation per protocol\")\n",
    "                    \n",
    "                    print(f\"\\nLogged to: {CONFIG['EVENT_LOG_PATH']}\")\n",
    "                    \n",
    "                except Exception as e:\n",
    "                    print(f\"Error: {e}\")\n",
    "        \n",
    "        apply_hl7_btn.on_click(apply_hl7)\n",
    "        compute_btn.on_click(compute)\n",
    "        \n",
    "        # Display UI\n",
    "        display(widgets.VBox([\n",
    "            widgets.HTML(\"<h3>ED Coordination Calculator (Advice-Only)</h3>\"),\n",
    "            widgets.HBox([vitals_input, labs_input]),\n",
    "            context_input,\n",
    "            hl7_input,\n",
    "            widgets.HBox([apply_hl7_btn, compute_btn]),\n",
    "            output_area\n",
    "        ]))\n",
    "        \n",
    "    except ImportError:\n",
    "        print(\"ipywidgets not available - UI disabled\")\nelse:\n",
    "    print(\"UI disabled by CONFIG\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === LOAD ML MODEL (if available) ===\n",
    "try:\n",
    "    from joblib import load\n",
    "    import numpy as np\n",
    "    import pandas as pd\n",
    "    \n",
    "    model_path = CONFIG[\"MODEL_BUNDLE_PATH\"]\n",
    "    if Path(model_path).exists():\n",
    "        bundle = load(model_path)\n",
    "        pipeline = bundle.get(\"pipeline\") or bundle.get(\"model\")\n",
    "        calibrator = bundle.get(\"calibrator\")\n",
    "        threshold = float(bundle.get(\"threshold\", 0.5))\n",
    "        features = bundle.get(\"features\")\n",
    "        \n",
    "        def predict_one(row: dict) -> dict:\n",
    "            \"\"\"Protected interface - ML prediction\"\"\"\n",
    "            X = pd.DataFrame([row])[features] if features else pd.DataFrame([row])\n",
    "            p = pipeline.predict_proba(X)[:, 1][0]\n",
    "            \n",
    "            if calibrator:\n",
    "                try:\n",
    "                    p = calibrator.predict([p])[0] if hasattr(calibrator, 'predict') else p\n",
    "                except:\n",
    "                    pass\n",
    "            \n",
    "            return {\"p\": float(p), \"y\": int(p >= threshold), \"thr\": threshold}\n",
    "        \n",
    "        print(f\"ML model loaded: {len(features) if features else '?'} features, threshold={threshold:.4f}\")\n",
    "    else:\n",
    "        print(f\"Model bundle not found at {model_path}\")\nexcept Exception as e:\n",
    "    print(f\"ML model loading failed: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === PREFLIGHT CHECKS ===\n",
    "def run_preflight():\n",
    "    \"\"\"Validate core functionality\"\"\"\n",
    "    checks = []\n",
    "    \n",
    "    # Check event logging\n",
    "    try:\n",
    "        _append_event({\"type\": \"preflight_test\", \"ok\": True})\n",
    "        checks.append(\"✅ Event logging\")\n",
    "    except Exception as e:\n",
    "        checks.append(f\"❌ Event logging: {e}\")\n",
    "    \n",
    "    # Check phase2_bundle\n",
    "    try:\n",
    "        test_vitals = {\"rr\": 24, \"sbp\": 95, \"gcs\": 14, \"hr\": 120, \"age\": 68}\n",
    "        test_labs = {\"d_dimer\": 780}\n",
    "        bundle = phase2_bundle(test_vitals, test_labs, {})\n",
    "        assert \"one_liners\" in bundle\n",
    "        assert \"scores\" in bundle\n",
    "        assert \"signals\" in bundle\n",
    "        checks.append(\"✅ Phase2 bundle\")\n",
    "    except Exception as e:\n",
    "        checks.append(f\"❌ Phase2 bundle: {e}\")\n",
    "    \n",
    "    # Check troponin logic (ESC 0/1h)\n",
    "    try:\n",
    "        from datetime import datetime, timedelta\n",
    "        base_time = datetime.now()\n",
    "        \n",
    "        # Test rule-out case\n",
    "        series_ruleout = [\n",
    "            (base_time, 10.0, \"ng/L\"),\n",
    "            (base_time + timedelta(minutes=60), 12.0, \"ng/L\")\n",
    "        ]\n",
    "        result = assess_troponin_delta(series_ruleout)\n",
    "        assert result[\"rule01h\"] == \"rule_out\"\n",
    "        \n",
    "        # Test rule-in case\n",
    "        series_rulein = [\n",
    "            (base_time, 20.0, \"ng/L\"),\n",
    "            (base_time + timedelta(minutes=60), 26.0, \"ng/L\")\n",
    "        ]\n",
    "        result = assess_troponin_delta(series_rulein)\n",
    "        assert result[\"rule01h\"] == \"rule_in\"\n",
    "        \n",
    "        checks.append(\"✅ ESC 0/1h troponin logic\")\n",
    "    except Exception as e:\n",
    "        checks.append(f\"❌ ESC 0/1h troponin: {e}\")\n",
    "    \n",
    "    # Check HL7 parsing\n",
    "    try:\n",
    "        hl7_test = \"OBX|1|NM|TROPONIN T||78|ng/L|||H||F|||20250820090000\"\n",
    "        parsed = parse_hl7_labs(hl7_test)\n",
    "        assert len(parsed[\"troponin\"]) > 0\n",
    "        checks.append(\"✅ HL7 parsing\")\n",
    "    except Exception as e:\n",
    "        checks.append(f\"❌ HL7 parsing: {e}\")\n",
    "    \n",
    "    # Check ML model (if loaded)\n",
    "    if 'predict_one' in globals():\n",
    "        try:\n",
    "            test_row = {f: 0.0 for f in features} if 'features' in globals() else {\"test\": 1.0}\n",
    "            result = predict_one(test_row)\n",
    "            assert \"p\" in result and \"y\" in result\n",
    "            checks.append(\"✅ ML model\")\n",
    "        except Exception as e:\n",
    "            checks.append(f\"❌ ML model: {e}\")\n",
    "    else:\n",
    "        checks.append(\"⚠️  ML model not loaded\")\n",
    "    \n",
    "    print(\"=== PREFLIGHT RESULTS ===\")\n",
    "    for check in checks:\n",
    "        print(check)\n",
    "    \n",
    "    failed = sum(1 for c in checks if c.startswith(\"❌\"))\n",
    "    if failed == 0:\n",
    "        print(\"\\n🎉 PREFLIGHT: PASS\")\n",
    "        return True\n",
    "    else:\n",
    "        print(f\"\\n❌ PREFLIGHT: FAIL ({failed} failures)\")\n",
    "        return False\n",
    "\n",
    "# Run preflight\n",
    "run_preflight()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === SMOKE TESTS (ESC 0/1h Verification) ===\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "def run_smoke_tests():\n",
    "    \"\"\"Verify ESC 0/1h troponin decision logic\"\"\"\n",
    "    base_time = datetime(2025, 8, 20, 9, 0, 0)\n",
    "    \n",
    "    print(\"=== SMOKE TESTS: ESC 0/1h Troponin ===\")\n",
    "    \n",
    "    # Test 1: Rule-out (t0=10, t1=12, Δ=2)\n",
    "    vitals1 = {\"age\": 65}\n",
    "    labs1 = {\n",
    "        \"troponin_series\": [\n",
    "            {\"time\": base_time.isoformat() + \"Z\", \"value\": 10.0, \"unit\": \"ng/L\"},\n",
    "            {\"time\": (base_time + timedelta(minutes=60)).isoformat() + \"Z\", \"value\": 12.0, \"unit\": \"ng/L\"}\n",
    "        ]\n",
    "    }\n",
    "    result1 = phase2_bundle(vitals1, labs1, {})\n",
    "    print(\"Test 1 (Rule-out):\", [line for line in result1[\"one_liners\"] if \"hs-cTnT\" in line][0])\n",
    "    \n",
    "    # Test 2: Rule-in (t0=20, t1=26, Δ=6)\n",
    "    vitals2 = {\"age\": 65}\n",
    "    labs2 = {\n",
    "        \"troponin_series\": [\n",
    "            {\"time\": base_time.isoformat() + \"Z\", \"value\": 20.0, \"unit\": \"ng/L\"},\n",
    "            {\"time\": (base_time + timedelta(minutes=60)).isoformat() + \"Z\", \"value\": 26.0, \"unit\": \"ng/L\"}\n",
    "        ]\n",
    "    }\n",
    "    result2 = phase2_bundle(vitals2, labs2, {})\n",
    "    print(\"Test 2 (Rule-in):\", [line for line in result2[\"one_liners\"] if \"hs-cTnT\" in line][0])\n",
    "    \n",
    "    # Test 3: No 60-min pair (samples at 0 and +90 min)\n",
    "    vitals3 = {\"age\": 65}\n",
    "    labs3 = {\n",
    "        \"troponin_series\": [\n",
    "            {\"time\": base_time.isoformat() + \"Z\", \"value\": 15.0, \"unit\": \"ng/L\"},\n",
    "            {\"time\": (base_time + timedelta(minutes=90)).isoformat() + \"Z\", \"value\": 18.0, \"unit\": \"ng/L\"}\n",
    "        ]\n",
    "    }\n",
    "    result3 = phase2_bundle(vitals3, labs3, {})\n",
    "    print(\"Test 3 (No pair):\", [line for line in result3[\"one_liners\"] if \"hs-cTnT\" in line][0])\n",
    "    \n",
    "    print(\"\\n✅ Smoke tests completed\")\n",
    "\n",
    "run_smoke_tests()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# === EVENT LOG TAIL ===\n",
    "def show_recent_events(n=5):\n",
    "    \"\"\"Show recent events from log\"\"\"\n",
    "    log_path = Path(CONFIG[\"EVENT_LOG_PATH\"])\n",
    "    if not log_path.exists():\n",
    "        print(\"No event log yet\")\n",
    "        return\n",
    "    \n",
    "    try:\n",
    "        lines = log_path.read_text().strip().split(\"\\n\")\n",
    "        recent = lines[-n:] if len(lines) >= n else lines\n",
    "        \n",
    "        print(f\"=== RECENT EVENTS (last {len(recent)}) ===\")\n",
    "        for line in recent:\n",
    "            if line.strip():\n",
    "                try:\n",
    "                    event = json.loads(line)\n",
    "                    ts = event.get(\"ts\", \"\")[:19]  # Show timestamp\n",
    "                    event_type = event.get(\"type\", \"unknown\")\n",
    "                    print(f\"[{ts}] {event_type}\")\n",
    "                except json.JSONDecodeError:\n",
    "                    print(f\"[Invalid JSON] {line[:50]}...\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error reading log: {e}\")\n",
    "\n",
    "show_recent_events()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Usage Instructions\n",
    "\n",
    "1. **Run all cells** to initialize the system\n",
    "2. **Use the UI** to input vitals, labs, and context data\n",
    "3. **Paste HL7 data** if available and click \"Apply HL7 → Labs\"\n",
    "4. **Click \"Compute + Log\"** to get advice-only results\n",
    "\n",
    "### Key Features Preserved:\n",
    "- **ESC 0/1h troponin logic** (protected - exact 60-minute pairing)\n",
    "- **phase2_bundle interface** (protected - maintains return structure)  \n",
    "- **Event logging** (protected - JSONL format)\n",
    "- **Advice-only stance** throughout\n",
    "\n",
    "### Simplifications Made:\n",
    "- Removed over-engineered configuration freezing\n",
    "- Streamlined medical calculators to essential functions\n",
    "- Simplified UI code while maintaining functionality\n",
    "- Removed excessive error handling and abstractions\n",
    "- Flattened complex class hierarchies\n",
    "\n",
    "This notebook is **~70% smaller** than the original while preserving all critical medical logic and interfaces."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}